### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by aahnik** [ramnes/notion-sdk-py#11]
https://github.com/ramnes/notion-sdk-py/blob/93f3ca9ac50a13d4d25bdb1afb6ff086c7284d59/setup.py#L20-L21

Install requires `httpx`, so I think, the project `requirements.txt` for that. 

The best point for using poetry is that we don't need to write the deps twice. Once in requirements.txt, and once in setup.py.

**Comment by aahnik** [comment]
`requirements.txt` is required for GitHub to generate dependency graphs. Github dependabot can alert us of any critical security updates in any package we depend on.

**Comment by ramnes** [comment]
IIRC dependabot can already parse setup.py. GitHub dependency graph is not really important to me, and I'd rather not duplicate the dependencies for this sole benefit. Although maybe it's smart enough to support a "fake" requirements.txt containing only something like `-e .`?

**Comment by aahnik** [comment]
If `requirements.txt` is there, then the developer can do 

```shell
pip install -r requirements.txt
```

For the end-user, who will `pip install notion-client` , this does not matter. But for people who will clone this repo, create a virtual env, and start developing, they need to need to manually install all required packages required by the `notion-client`.

Currently `notion-client` only depends on `httpx`, (so i need to `pip install httpx`) but in the future, as we provide more features, we may need other dependencies, then `pip install x y z` may become cumbersome.

It will be great, if a contributing guidelines is written, for new developers who want to contribute to this repo.

**Comment by ramnes** [comment]
Yeah, I do agree that a requirements.txt file makes contributing easier by respecting people habits. :) What I don't want is to duplicate the list of dependencies, hence the `-e .` suggestion, which I think would make everyone happy.

**Comment by aahnik** [comment]
yes, that's right. But once, editable installs are available for `pyproject.toml`, I think, we should move to poetry.

**Comment by ramnes** [comment]
Yeah maybe, let's discuss it again when that happens. Thanks your contribution!
