### ISSUE TITLE
Update to the 2022-02-22 version

### ISSUE THREAD

**Issue by mutt0-ds** [ramnes/notion-sdk-py#125]
Hi! 
I see that the [API has been updated to the new version](https://developers.notion.com/changelog/releasing-notion-version-2022-02-22), which has a couple of cool features: one I'm interested in is the chance to add advanced types of block like toggles to the [BlocksChildrenEndpoint](https://github.com/ramnes/notion-sdk-py/blob/d1819debf6ed24996bfd21be7adbe3d442f3b1c6/notion_client/api_endpoints.py#L18), which is not working with the current version of the library. 

If I try to append a children to an existing page with the [example code for a toggle](https://developers.notion.com/reference/block#toggle-blocks) provided by Notion I get an error saying to update the API version.

I think that it's solvable by upgrading the version [here](https://github.com/ramnes/notion-sdk-py/blob/d1819debf6ed24996bfd21be7adbe3d442f3b1c6/notion_client/client.py#L50), but since it's not backward compatible I'm asking here if there's something to be aware of before proceeding.

**Comment by ramnes** [comment]
Updated and released. Thanks!
