### ISSUE TITLE
Adding A Formatting Option

### ISSUE THREAD

**Issue by VisakhChekur** [ramnes/notion-sdk-py#134]
I would like to add a formatter that will automatically create the dictionaries in their correct format based on the property. I think this will help make the code just more readable since without it there are just extremely large dictionaries and a whole bunch of curly braces. I personally use this formatter for my own scripts that I use to automate some things on Notion.

For example:

Before using a formatter:
```
create_details = {
    "parent": DB_ID,
    "properties": {
        "some date property": {
            "date": {
                "start": "starting date",
                "end": "ending date",
            }
        },
        "some multi select property": {
            "multi_select": [
                {
                    "name": "option name"
                },
                {
                    "name": "option name",
                    "color": "option color"
                }
            ]
        },
        "some select property": {
            "select": {
                "option": "option name",
                "color": "option color"
            }
        }
    }
}
```

After using a formatter:
```
# this is needed because `formatter.multi_select` takes a dictionary
# as the input
multi_select_options = {
    "option one": "default",
    "option two": "color"
}
# the same dictionary, but using the formatter
create_details = {
    "parent": DB_ID,
    "properties": {
        "some date property": formatter.date("start date", "end date"),
        "some multi select property": formatter.multi_select(multi_select_options),
        "some select property": formatter.select("option name", "option color")
    }
}
```

**Comment by ramnes** [comment]
Hi @VisakhChekur!

At the moment I'm not interested in diverging from the official Notion SDK (and API), so this will not make it into the tree.

That being said, feel free to share your formatter as a gist or repository and advertise it here! I'm sure it can help some people.

**Comment by VisakhChekur** [comment]
@ramnes That's completely fine :) Thank you for considering this though.
