### ISSUE TITLE
notion_client.errors.APIResponseError: Value is expected to be rich_text. Link is expected to be files.

### ISSUE THREAD

**Issue by AxDSan** [ramnes/notion-sdk-py#136]
Issue: when I try to add data to a database, I get errors because of the properties that are expected are incorrectly setup in the database, and the error returned doesn't helps.

The Following an example from: [https://github.com/ramnes/notion-sdk-py/wiki/Examples#crud](https://github.com/ramnes/notion-sdk-py/wiki/Examples#crud)

I have had incorrectly created/setup the following properties in my db:

(Property Name: Type)
Name: Text
Tags: Multi-Select
Value: Text
Link: Files

Therefore the APIResponseError returned:
`Value is expected to be rich_text. Link is expected to be files.`
but this is wrong, since what's the error is saying is that the type that `Value` is supposed to be expecting is "rich_text", but it's actually telling me the actual property type... instead it should have returned something like this:

`notion_client.errors.APIResponseError: Value is expected to be Number. Link is expected to be URL.`

This took me a while to understand, because I hadn't look at the schema that it's already setup:

```python
new_page_props = {
        'Name': {'title': [{'text': {'content': f"My Page of {rand_page_type} {page_id}"}}]},
        'Value': {'number': page_id},
        'Link': {'type': 'url', 'url': f"http://examples.org/page/{page_id}"},
        'Tags': {'type': 'multi_select', 'multi_select': [{'name': rand_page_type}]}
    }
```

Stack Trace:
```
Traceback (most recent call last):
  File "C:\Users\user\Documents\project\bots\test_notion_api.py", line 44, in <module>
    notion_page = notion.pages.create(
  File "C:\Users\maris\miniconda3\envs\an_env\lib\site-packages\notion_client\api_endpoints.py", line 197, in create
    return self.parent.request(
  File "C:\Users\maris\miniconda3\envs\an_env\lib\site-packages\notion_client\client.py", line 192, in request
    return self._parse_response(response)
  File "C:\Users\maris\miniconda3\envs\an_env\lib\site-packages\notion_client\client.py", line 124, in _parse_response
    raise APIResponseError(response, body["message"], code)
notion_client.errors.APIResponseError: Value is expected to be rich_text. Link is expected to be files.

Process finished with exit code 1
```

Solution: Be able to get a proper error  message with the actual type that's expected by the read values, and not the ones that are setup in the database.

**Comment by ramnes** [comment]
Hey there!

I don't understand why you feel the error is wrong; if your database expects a text and that you try to send a number instead, "Value is expected to be rich_text" seems quite explicit to me.

Anyway, API errors are handled by Notion, I can't do much since I'm not part of Notion's team. You can reach their support at [developers@makenotion.com](mailto:developers@makenotion.com).

Feel free to comment if I can help in any way.

**Comment by AxDSan** [comment]
It just clicked to me, as I was expecting the error to address my local schema, and not the one in the db! I was totally confused for a second, but then I understood, your reply also made me thinker a little bit more on this :D
