### ISSUE TITLE
Implement notion-sdk-js helpers

### ISSUE THREAD

**Issue by ramnes** [ramnes/notion-sdk-py#137]
Notion now implements a few helpers: https://github.com/makenotion/notion-sdk-js/pull/320

Let's port them back here with the same API!

**Comment by ramnes** [comment]
@jheddings You may be interested in these, as a higher-level base for notional. :)

**Comment by ramnes** [comment]
The README examples are also to port back along the way: https://github.com/makenotion/notion-sdk-js/pull/325

**Comment by mutt0-ds** [comment]
It looks interesting, I'll be happy to contribute!
