### ISSUE TITLE
Support for `is_inline` on databases

### ISSUE THREAD

**Issue by weallwegot** [ramnes/notion-sdk-py#138]
Hi, I think they recently added support for `is_inline` on databases. Not sure if I understand the sdk well but would the update be at this line to just include a new argument in the `pick` function?

[changelog announcing new support](https://developers.notion.com/changelog/changes-for-june-6-june-20-2022)

https://github.com/ramnes/notion-sdk-py/blob/6b0fb3e0777338a0e36d0f5a2f7f85f88da63210/notion_client/api_endpoints.py#L156

**Comment by ramnes** [comment]
Yes, that's it!

We are lagging a bit behind notion-sdk-js and I think there are a few `pick` arguments to add, not just `is_inline`. :)

**Comment by ramnes** [comment]
Closed with #154
