### ISSUE TITLE
Create new property / column inside page with python sdk fails

### ISSUE THREAD

**Issue by alxizr** [ramnes/notion-sdk-py#149]
Hi, 

I am facing difficulties with the latest, most current notion official sdk to create a new column inside a table within a page. According to the docs, if I want to update the page with a new property I need to name the property key and the value should be as it is defined under [property schema object](https://developers.notion.com/reference/property-schema-object).

I tried using both the create and update client methods but I am getting the same error with both of them. **notion_client.errors.APIResponseError: URL2 is not a property that exists.**

I am trying to create a column / property of type url and set a value to it

this is the code block, would like for some feedback

`
notion.pages.create(**{
    "parent": {"database_id": <my_database_id>},
    "page_id": <"my_page_id">,
    "properties": {
        "My_URL_Column": {
            "url": "www.abc123.com",
            "type": "url"
        }
    }
})
`

Thank you in advanced

**Comment by alxizr** [comment]
never mind! i figured it out!

**Comment by ramnes** [comment]
You may want to explain what the problem was for future readers :)

![https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

**Comment by alxizr** [comment]
the problem appeared to be with the way the sdk is written and the lack of examples in my opinion. This specific action is a 2 way process, rather than only one. First you need to declare the column as an empty object, according to the column type and property schema and only then do the actual operation intended to begin-with with all the details you want that column to hold

**Comment by ramnes** [comment]
Did you see the ["first project" example](https://github.com/ramnes/notion-sdk-py/blob/1cd184f1a2c625e0c7432fa42438e7e88730e44d/examples/first_project/script.py)? Didn't help?

Also, it's weird that you had to create and then update the page, there should be no difference between the two endpoints and you should be able to create a page with the proper field value from the start. 🤔

**Comment by alxizr** [comment]
@ramnes 

Once I hit the wall with this issue I went back to the sources: documentation and the example. With a lot of trial and error & trying to read between the lines with the exceptions Notion was throwing at me, I figured it out to be a 2 step process. This is the piece of code that solved my issue and apparently there is no other way.

`
#step 1
notion.databases.update(**{
    "database_id": NOTION_DATABASE_ID,
    "properties": {
        
        # example column / property I want to add to the database schema
        "My_Url": {
            "url": {}           # to create new column/property
        }
        
    }
})

#step 2
notion.pages.create(**{
    "page_id": myPageId,
    "parent": {
        "database_id": NOTION_DATABASE_ID
    },
    "properties": {
    
        # my new column / property I inserted to the database
        "My_Url": {
            "url": "www.abc123.com",
            "type": "url"
        },
        
        # preexisting column / property
        "Name": {
            "title": [{
                "text": {
                    "content": "this is a new name in this row"
                }
            }]
        }
    }
})
`

I think that what threw me off from the get go was that I relied on the postman examples heavily and when I copy and pasted the same requests into my code it did not work. You can see for example new page creation is not working as it is published. You need to mutate the database / page schema beforehand, and that is what makes it a 2 step process.
