### ISSUE TITLE
How to use `iterate_paginated_api`?

### ISSUE THREAD

**Issue by yedhrab** [ramnes/notion-sdk-py#167]
* Documentation says this but it doesn't work. How can i access these methods?

> I have just recognize `pip` installation method is outdated and `helpers` doesn't contain these methods (:

```python
from notion_client.helpers import iterate_paginated_api

for block in iterate_paginated_api(
    notion.databases.query, database_id="897e5a76-ae52-4b48-9fdf-e71f5945d1af"
):
    # Do something with block.
    ...
```

**Comment by ramnes** [comment]
Most likely it wasn't working because they weren't included in the latest release (1.0.0).

I just released 2.0.0, so you should now able to use them after a simple `pip install -U notion-sdk-py`. :)

Feel free to comment if you're still having troubles.
