### ISSUE TITLE
[Docs] Resource not found when opening docs from main 

### ISSUE THREAD

**Issue by endriu00** [ramnes/notion-sdk-py#176]
Hey, I was trying to access the repo documentation following the path `docs/summary` and clicking on one of the links outlined there, but the links lead to a non-existing page!
I am on the main branch for reference

**Comment by ramnes** [comment]
Hey,

The docs are auto-generated and thus not browsable in the main branch on GitHub directly.

This is where you want to browse the docs: https://ramnes.github.io/notion-sdk-py/
