### ISSUE TITLE
[error] AttributeError: 'str' object has no attribute 'logger'

### ISSUE THREAD

**Issue by windwindwa** [ramnes/notion-sdk-py#192]
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/48432322/235350073-5775506c-9e78-408f-8251-f943c6d934d2.png">

**Comment by ramnes** [comment]
I guess you're giving the token directly rather than with the `auth` keyword, which is not how it's meant to be used; correct usage is: `notion = Client(auth="...")`, not `notion = Client("...")`.
