### ISSUE TITLE
Image upload error when create a new notion page

### ISSUE THREAD

**Issue by hx3333** [ramnes/notion-sdk-py#214]
my_block = [{'image': {'caption': [], 'type': 'external', 'external': {'url': 'https://mmbiz.qpic.cn/mmbiz_gif/YOBosIBzibxFvlzx4aic86IVpzD4hmib8YcaLJgCH1DaMmkMGbD0RDkMDBOUOOvCFEiab9In6tHIAdJicf5Vtk81UHw/640?wx_fmt=gif'}}}]
then raise:
notion_client.errors.APIResponseError: Content creation Failed. Fix the following: 
Invalid image url.

I'm not quite sure what the problem is. Although the error message indicates a URL issue, when I directly use this URL to add a page in the Notion client, the image displays normally.Has any friend encountered this problem? Looking forward to kind-hearted people's responses to help me 😢

**Comment by ramnes** [comment]
This error is raised by the API, not notion-sdk-py, so I'm converting this as a discussion.
