### ISSUE TITLE
Alternative for `DatabasesEndpoint.list()`

### ISSUE THREAD

**Issue by baniasbaabe** [ramnes/notion-sdk-py#216]
Since `DatabasesEndpoint.list()` is deprecated, are there any other ways to query all available databases?

**Comment by ramnes** [comment]
> ### Search pages for more details
> This endpoint is deprecated and is only available on API version "2021-08-16" and earlier. Use the [Search API](https://developers.notion.com/reference/post-search) instead. This endpoint will only return explicitly shared databases, while search will also return child pages. This endpoint's results cannot be filtered, while search can be used to match on page title.

https://developers.notion.com/reference/get-databases
