### ISSUE TITLE
notion.blocks.append not accessible

### ISSUE THREAD

**Issue by chandrashan** [ramnes/notion-sdk-py#225]
Hi,

Just tried to use the notion.blocks.append functionality - which seems to exist on the BlocksChildrenEndpoint, but not on the BlocksEndpoint.

Not sure if I'm doing something wrong, but this means I cannot access the notion.blocks.append item.

Any suggestions?

**Comment by ramnes** [comment]
Hey there,

Please read Notion's API docs. There is no such thing as a `notion.blocks.append` functionality. `notion.blocks.children.append` is what you want to use.

https://developers.notion.com/reference/patch-block-children
