### ISSUE TITLE
Wrong response when querying database rollup field with ascending/descending sort

### ISSUE THREAD

**Issue by S-A-M-J** [ramnes/notion-sdk-py#230]
When querying a notion database based on a sort ascending/descending of rollup field the response is not sorted in any way, meaning the ascending/descending sort did not work. Moreover querying ascending and descending result in the same response. 
However when i query a normal number field the sorts do work. Furthermore this query worked 2 months ago and has to have broken in the meantime.

Relevant query code
[file.txt](https://github.com/ramnes/notion-sdk-py/files/14016419/file.txt)

**Comment by ramnes** [comment]
Not related to the client, works for me:

```python
import asyncio
import os
from pprint import pprint

from notion_client import AsyncClient, Client


async def main_async() -> None:
    notion = AsyncClient(auth=os.environ["NOTION_TOKEN"])
    users = await notion.users.list()

    database_id = "c4c692fcde4e4bc4a4423ab76e54f89d"

    print("Ascending:")
    response = await notion.databases.query(**{
	"database_id": database_id,
	"sorts": [
	    {
	        "property": "Name",
	        "direction": "ascending"
	    }
	],
    })
    for result in response["results"]:
        print("* " + result["properties"]["Name"]["title"][0]["plain_text"])

    print("Descending:")
    response = await notion.databases.query(**{
	"database_id": database_id,
	"sorts": [
	    {
	        "property": "Name",
	        "direction": "descending"
	    }
	],
    })
    for result in response["results"]:
        print("* " + result["properties"]["Name"]["title"][0]["plain_text"])

asyncio.run(main_async())
```

Output:

```python
Ascending:
* 1
* 2
* 3
Descending:
* 3
* 2
* 1
```

I guess something's wrong with your code?

**Comment by ramnes** [comment]
Just saw that you're mentioning that you're trying to sort on a Rollup field. That's probably just not supported by Notion API, did you try with another client?
