### ISSUE TITLE
Add a GitHub CI cron job that open issues here for new Notion API changelog entries

### ISSUE THREAD

**Issue by ramnes** [ramnes/notion-sdk-py#234]
Most of the development / maintenance of this package is tied to [Notion API changelog](https://developers.notion.com/page/changelog).

I already receive a notification every time a change happens in notion-sdk-js (watch [ramnes/notion-sdk-js](https://github.com/ramnes/notion-sdk-js) if you want them too), but sometime I misinterpret a commit and skip important changes.

A new issue here every time there's a new entry in the official changelog would be a better way to follow upstream changes!

**Comment by trancethehuman** [comment]
Glad that this project is active :)

**Comment by ramnes** [comment]
Yes, it is. I would just like to see a bit more contributions from the community, I'm feeling quite alone these days. :)

**Comment by trancethehuman** [comment]
@ramnes do you have a list of issues for newcomers? I'll pick a few and work on them.

About to build Notion integration in my FastAPI app this month.

**Comment by AlexPantyukhin13** [comment]
Has anyone already taken it ?

**Comment by ramnes** [comment]
Go ahead!

**Comment by MassimoGennaro** [comment]
Hey @ramnes,

I recently started using this library for a project and thought I’d try to give back! I saw this issue and put together a potential solution in my fork [here](https://github.com/MassimoGennaro/notion-sdk-py/tree/notion-api-changelog-cron-job).

What I did:

- Wrote a script that grabs the changelog, convert HTML to Markdown, saves it to a file to track what’s already been processed and opens issues only for new updates ([here](https://github.com/MassimoGennaro/notion-sdk-py/issues) two examples).

- Added a workflow to run the script every night.

Let me know what you think about this solution. Happy to tweak it or clean things up and open a PR if it seems useful.

**Comment by ramnes** [comment]
Hey @MassimoGennaro,

That's awesome, thank you so much for the help! It definitely seems useful, and I'd be really happy to get this merged. :)

Top of mind right now:
* What would you think if we'd save less, e.g. only the date, title, and content md5?
* I think it would be great to save the original blog post URL (using their anchor) and add it to the bottom of the issue.
* We really need to make sure the script fails if their HTML structure changes, so that we can adapt and avoid doing crazy things with GitHub's API.

Don't feel obliged to make these changes, but please open a PR. Thanks again!

**Comment by MassimoGennaro** [comment]
Hi @ramnes 
I had some spare time and work on the changes.

- Now we save only date, title, and content md5 on the _known_entries.json_ file (example [here](https://github.com/MassimoGennaro/notion-sdk-py/blob/notion-api-changelog-cron-job/.github/scripts/known_entries.json)). The content md5 is also used to identify new entries.
- The issue now contains the anchor URL the the original changelog entry and I assumed that a new label _changelog_ can be added to tag these kind of issues (example [here](https://github.com/MassimoGennaro/notion-sdk-py/issues/123)). If you agree, please remember to add this new label 😉 
- Now the script has some exception handlers to interrupt it when errors occur (including not expected HTML structure)

I tested it on my fork and everything seems working fine. I'm opening a PR!

**Comment by ramnes** [comment]
Implemented by @MassimoGennaro in #244. Thanks again!
