### ISSUE TITLE
ORM for notion databases

### ISSUE THREAD

**Issue by aahnik** [ramnes/notion-sdk-py#33]
Django ORM, sqlalchemy etc, are examples where you write python classes and call python functions, but under the hood SQL queries get carried out.

It would be great to have an ORM, that under the hood would carry out various interactions using Notion API. For the end user, it will be a high level experience.

Example usage

```python

# a vague example usage

class Student(NotionBaseModel):
    name: Title
    address: Text
    last_edited: LastEditedTime

student = Student("Aahnik","India") # will add a row to the table
```

**Comment by Jeadie** [comment]
I think you will find this is very similar to the implementation I am working on using dataclasses for easy instantiation and access.

**Comment by ramnes** [comment]
Let's make this a discussion. :)
