### ISSUE TITLE
Package using poetry for a better life

### ISSUE THREAD

**Issue by aahnik** [ramnes/notion-sdk-py#4]
setup.py is a old method. pyproject.toml is modern, and poetry is very convenient.

Should I open a pr ?

**Comment by ramnes** [comment]
Hey @aahnik, thanks for the issue and offer!

Poetry is indeed a much better tool but as good and widely used as it is, it's not what I would call standard, yet. For example, the thing that's holding me back the most is the lack of support for editable installs. While they don't make sense in the Poetry world, not everyone uses Poetry.

From my experience, a setup.py file is still the most portable way for libraries, i.e. it doesn't get in the path of anyone, whatever tool they're using for their application development. I feel that Poetry and others bring a lot of value for a project developer, but not really for libraries end users. I'm still open to discussion though!

**Comment by ramnes** [comment]
Moving this to a discussion. :)
