### ISSUE TITLE
Question: the struggle is real

### ISSUE THREAD

**Issue by ChrisChross** [ramnes/notion-sdk-py#46]
Hi Guys,

this is more of a question i have. I got started and tried the one example to display the users.
That worked fine. However, after that i tried to find a notion page by it's id. 
So my first question, where to find that `page_id` ? I thought about it's the hash value on the link
of the notion page (however, in the example it includes `-` and in the hash not. 

After that, i just wanted to list all pages that are available, how to do that? 
I could not find anything like `notion.pages.list()` . 

Last but not least, and more of a general understanding question what are blocks? 
How to see what blocks are saved? 

Sorry if this questions are to simple for you, peeps. 

Cheers
Chris

**Comment by aahnik** [comment]
> So my first question, where to find that page_id ?

Read this https://github.com/ramnes/notion-sdk-py/discussions/31

> what are blocks?

From Notion HQ: “A block is any single piece of content you add to your page, like a to-do item, an image, a code block, an embedded file, etc. Think of your page as being made up of these building blocks.”
