### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by ramnes** [ramnes/notion-sdk-py#48]

**Comment by aahnik** [comment]
What's your planned format? CHANGELOG.md or using the GitHub Releases? 

I prefer the second, as there is no large file to maintain. Every release is tied to a git tag. In the release description the changes could be described.

A good example is https://github.com/cli/cli/releases

**Comment by ramnes** [comment]
Good idea! Went that way, thanks: https://github.com/ramnes/notion-sdk-py/releases
