### ISSUE TITLE
Update method of PagesEndpoint class never handles archived pages

### ISSUE THREAD

**Issue by Thompsonmina** [ramnes/notion-sdk-py#65]
Calling something like 
`
	archivedpage = notion.pages.update(page_id, **{"archived":True, "properties":properties})
`
will never result in the page being archived. Tested calling the same route on curl and it works

Did some digging and i think i figured out where the bug is from,
```
def update(self, page_id: str, **kwargs: Any) -> SyncAsync[Any]:
        return self.parent.request(
            path=f"pages/{page_id}",
            method="PATCH",
            body=pick(kwargs, "properties"),
            auth=kwargs.get("auth"),
        )
```
The line `body=pick(kwargs, "properties")` in the update method doesn't pick up the archived keyword from kwargs, resulting in only the properties item being added to body

**Comment by ramnes** [comment]
Fixed in with #66
