### ISSUE TITLE
vscode jupyter os.environ key error

### ISSUE THREAD

**Issue by maxhoheiser** [ramnes/notion-sdk-py#79]
Hi guys, when using vs code with conda envs, I get a key error for loading the Client with my key via
`notion = Client(auth=os.environ['TOKEN']`
i get this output

```
KeyError: 'TOKEN'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/var/folders/cq/tw7v96zx0sx59ptff9z4d6hw0000gn/T/ipykernel_14685/1136862354.py in <module>
----> 1 notion = Client(auth=os.environ["TOKEN"])

~/miniforge3/envs/pipeline/lib/python3.8/os.py in __getitem__(self, key)
    673         except KeyError:
    674             # raise KeyError with the original key value
--> 675             raise KeyError(key) from None
    676         return self.decodevalue(value)
    677 

KeyError: 'TOKEN'
```
anybody came across the same issue, or knows how to fix it?

**Comment by ramnes** [comment]
Hi @maxhoheiser,

Your code expect a `TOKEN` environment variable, so you have to pass the environnement variable to your program. I do not use VS Code so I don't know how you tell it to run Python with particular environment variable.

What I know though is that it's unrelated to notion-sdk-py, so I'll close this issue (but people can still answer!)
