### ISSUE TITLE
Missing examples of creating databases

### ISSUE THREAD

**Issue by stereorobin** [ramnes/notion-sdk-py#82]
Hello,
I'm having problems creating a database, mostly due to lack of any examples.
I can create a page just fine, but am having problems with databases.
I think I just get type/format of the title and properties wrong.

Would be great to have an example of how to create a database with a title and a text property.

Thanks for your great work!

**Comment by ramnes** [comment]
Uh, this has been fixed a long time ago actually! Thanks for raising the issue.
