### ISSUE TITLE
Trying to create a page with an icon, but I get a page...without an icon

### ISSUE THREAD

**Issue by Vermoot** [ramnes/notion-sdk-py#91]
Hi!

Just as the title says, I'm trying to create a page *with an icon*, but I fail to see where I'm going wrong about it. Here's my code:

```python
notion.pages.create(parent={"database_id": projects_db},
                           icon={"emoji": "⚜️", "type":"emoji"},
                           properties={"Nom": {"title": [{"text": {"content": "Blabla"}}]}})
```

What I get is a page, in the right database, with the right name, but no icon. Am I missing something?

Thanks!

**Comment by victorterancas** [comment]
I think it is because the symbol is not in notion library, try with one supported by them such us 🧪.
```
notion.pages.create(parent={"database_id": projects_db},
                           icon={"emoji": "🧪", "type":"emoji"},
                           properties={"Nom": {"title": [{"text": {"content": "Blabla"}}]}})
```
