### ISSUE TITLE
Impossible to clear a field

### ISSUE THREAD

**Issue by Raoul555** [ramnes/notion-sdk-py#92]
According to notion support, to clear a field (reset its value), you should do:
    {
        "properties": {
        "Sponsor": { "select": null }
    }

This is not possible with the current version. The best that we can do is:
    {
        "properties": {
        "Sponsor": { "select": None }
    }

but it is not accepted by notion.

**Comment by ramnes** [comment]
What error do you get? I wonder if that's related to #94, seems quite similar.

**Comment by ramnes** [comment]
Please post the error you receive and I will reopen.
