### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by bergercookie** [ramnes/notion-sdk-py#98]
Hi @ramnes ,

I just wanted to say thanks for this project! :-)

I used it to implement a first version of my taskwarrior <-> notion sync: https://github.com/bergercookie/taskwarrior-syncall/blob/master/readme-notion.md

**Comment by ramnes** [comment]
Thank you very much for the kind words! Please keep participating and contributing to notion-sdk-py, that would be the most rewarding appreciation to me! 😉
